[project]
name = "pflacco"
version = "1.2.2"
description = "Feature-based Landscape Analysis of Continuous and Constrained Optimization problems."
readme = "Readme.md"
requires-python = ">=3.10"
dependencies = [
  "numdifftools>=0.9.42",
  "numpy>=2",
  "pandas>=2.3.3",
  "pydoe>=0.9.9",
  "salib>=1.5.2",
  "scikit-learn>=1.7.2",
  "scipy>=1.15.3",
]

[dependency-groups]
dev = [
    "ioh>=0.3.22",
    "deptry>=0.25.1",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.lint.isort]
force-single-line = true

[build-system]
requires = ["uv_build>=0.8,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pflacco"
module-root = ""
