# Build package and run tests
name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.10", "3.11"]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.version}}
        cache: 'pip'
    - run: python -m pip install --upgrade pip pytest
    - run: python -m pip install -r requirements.txt
    - run: python -m pip install .
    - run: pytest tests/
